## Description
This notebook demonstrates the usage of Unstructured Data Ingestion APIs. 

## Usage Instructions
Run each cell sequentially to execute the notebook.
Note some cells are for reference and in order to not accidently excute them, they are marked as "Markdown".

In [7]:
IPADDRESS = "localhost" #Replace this with the correct IP address
UNSTRUCTURED_DATA_PORT = "8086"

## Document Ingestion
#### Get health of the document ingest service

In [9]:
## CHRIS - list all documents
import requests

IPADDRESS = "localhost"  # Replace with the correct IP address if needed
UNSTRUCTURED_DATA_PORT = "8086"  # Replace with the correct port if needed

# Check health first
health_url = f'http://{IPADDRESS}:{UNSTRUCTURED_DATA_PORT}/health'
response = requests.get(health_url, headers={'accept': 'application/json'})
print("Health Check:", response.status_code, response.json())

# Now get the documents
docs_url = f'http://{IPADDRESS}:{UNSTRUCTURED_DATA_PORT}/documents'
response = requests.get(docs_url, headers={'accept': 'application/json'})

if response.status_code == 200:
    docs = response.json().get("documents", [])
    print("Available Documents:")
    for doc in docs:
        print(doc)
else:
    print("Failed to get documents. Error:", response.status_code, response.text)

Health Check: 200 {'message': 'Service is up.'}
Available Documents:
GEFORCE_TRIANGULATION_TEE_UNISEX_Apparel_Mens
FULL_ZIP_NEURAL_HOODIE_UNISEX_Apparel_Mens
TROIKA_CONSTRUCTION_PEN_Office_Office
NVIDIA_JETSON_ORIN_NANO_DEVELOPER_KIT_NVIDIA_Electronics_Jetson
NORTH_FACE_MENS_TREKKER_JACKET_Apparel_Mens
INTENSITY_CLIC_GEL_PEN_Office_Office
TIMBUK2_VAPOR_BACKPACK_TOTE_-_GRAPHITE_Bags_Bags
MENS_BEYOND_YOGA_TAKE_IT_EASY_PANT_-_DARKEST_NIGHT_Apparel_Mens
NVIDIA_SMALL_INFINITY_MOUSEPAD_Office_Office
FLUX_BONDED_JACKET_WOMENS_LIGHT_HEATHER_Apparel_Womens
NVIDIA_GEFORCE_RTX_4090_NVIDIA_Electronics_Geforce
MENS_BEYOND_YOGA_TAKE_IT_EASY_SHORTS_Apparel_Mens
NVIDIA_SHIELD_TV_PRO_2019_NVIDIA_Electronics_Shield
GEFORCE_RTX_4070_SUPER_User_Guide_Rev1
VICTORINOX_LAPTOP_WOMENS_TOTE_Bags_Bags
CHAMPION_REVERSE_WEAVE_CREWNECK_UNISEX_Apparel_Mens
25_OZ._NVIDIA_ICONOGRAPHY_BOTTLE_Drinkware_Drinkware
PRODIR_PATTERN_PEN_Office_Office
AUTONOMOUS_TIME_TRAVELER_TEE_UNISEX_Apparel_Mens
NVIDIA_GEFORCE_RTX_4070_SUPER_NVIDIA_Electronics_Geforce
14_OZ._A_NEW_BREED_OF_INNOVATION_MUG_Drinkware_Drinkware
LONG_SLEEVE_PERFORMANCE_SHIRT_WOMENS_Apparel_Womens
NVIDIA_GREEN_LABEL_BEANIE_Apparel_Mens
OGIO_STRATAGEM_BACKPACK_Bags_Bags
physics
GIFT_BAG_Bags_Bags
GEFORCE_LOGO_HIGH_DENSITY_TEE_UNISEX_Apparel_Mens
NVIDIA_ATHLETIC_CREW_SOCKS_Apparel_Mens
14_OZ._I_AM_AI_MUG_Drinkware_Drinkware
OGIO_CATALYST_DUFFEL_-_BLACK_Bags_Bags
WOMENS_BEYOND_YOGA_MOVEMENT_SKIRT_Apparel_Womens
LONG_SLEEVE_PERFORMANCE_SHIRT_MENS_Apparel_Mens
GEFORCE_NOW_50_MEMBERSHIP_GIFT_CARD_NVIDIA_Electronics_Geforce
NVIDIA_GEFORCE_RTX_4080_NVIDIA_Electronics_Geforce
WOMENS_BEYOND_YOGA_REFOCUS_TANK_Apparel_Womens
UNISEX_TMYBTMYS_CUDA_TEE_Apparel_Mens
NORTH_FACE_WOMENS_TREKKER_JACKET_Apparel_Womens
WOMENS_BEYOND_YOGA_IN-STRIDE_PULLOVER_-_BLACK_Apparel_Womens
FLUX_BONDED_JACKET_2.0_MENS_LIGHT_HEATHER_Apparel_Mens
NVIDIA_FLOW_LARGE_MOUSEPAD_Office_Office
MENS_LOGO_TEE_Apparel_Mens
MARINE_LAYER_CORBET_FULL_ZIP_VEST_MENS_Apparel_Mens
COMPUTER_CARE_KIT_Office_Office
20_OZ._ELEMENTAL_WATER_BOTTLE_Drinkware_Drinkware
TOPO_ROVER_TECH_PACK_Bags_Bags
NVIDIA_NIMBLE_CHAMP_PRO_CHARGER_Lifestyle_Lifestyle
WIREFRAME_EYE_GRAPHIC_TEE_UNISEX_Apparel_Mens
NVIDIA_LIGHTWEIGHT_HOODIE_Apparel_Mens
TOTE_BAG_Bags_Bags
NIKE_2.0_POLO_MENS_Apparel_Mens
MENS_LULULEMON_ABC_JOGGER_Apparel_Mens
COTTON_TOUCH_POLO_MENS_Apparel_Mens
GEFORCE_RTX_4080_SUPER_User_Guide_Rev1
MENS_BEYOND_YOGA_CREW_T-SHIRT_-_DARKEST_NIGHT_Apparel_Mens
PORTABLE_FOLDING_CHAIR_Lifestyle_Lifestyle
NVIDIA_GEFORCE_HAT_Apparel_Mens
NVIDIA_GEFORCE_RTX_4060TI_8GB_NVIDIA_Electronics_Geforce
WOMENS_POCKET_LEGGINGS_Apparel_Womens
cs
32_OZ._NVIDIA_ICONOGRAPHY_BOTTLE_Drinkware_Drinkware
TIMBUK2_LAPTOP_SLEEVE_-_2_SIZES_Office_Office
14_OZ._NVIDIA_LOGO_MUG_Drinkware_Drinkware
NVIDIA_SHIELD_TV_2019_NVIDIA_Electronics_Shield
NVIDIA_LICENSE_PLATE_FRAME_Lifestyle_Lifestyle
UNISEX_INSPIRE_365_TEE_Apparel_Mens
CLUBMAN_SUNGLASSES_Lifestyle_Lifestyle
TITLEIST_PRO_V1_HALF_DOZEN_GOLF_BALLS_Lifestyle_Lifestyle
40_OZ._STANLEY_QUENCHER_TUMBLER_Drinkware_Drinkware
14_OZ._VISUAL_PURR-CEPTION_MUG_Drinkware_Drinkware
ANKLE_SOCK_UNISEX_Apparel_Mens
WOMENS_V-NECK_TEE_Apparel_Womens
RULER_Office_Office
RULER_2.0_Office_Office
I_AM_AI_TEE_MENS_Apparel_Mens
GEFORCE_ABSTRACTION_TEE_UNISEX_Apparel_Mens
FAQ
NVIDIA_GEFORCE_RTX_4070_NVIDIA_Electronics_Geforce
GeForce_RTX_4090_QSG_Rev1
GeForce_RTX_4070_QSG_Rev1
I_AM_AI_TEE_WOMENS_Apparel_Womens
MARINE_LAYER_CORBET_FULL_ZIP_VEST_WOMENS_Apparel_Womens
12_MARLED_KNIT_CUFF_BEANIE_Apparel_Mens
YOUTH_LOGO_TEE_Apparel_Kids
TIMBUK2_LAPTOP_SLEEVE_-_2_SIZES_Bags_Bags
math
TIMBUK2_PARKSIDE_BACKPACK_2.0_Bags_Bags
NVIDIA_ICONOGRAPHY_KRAFT_POCKET_JOURNAL_-3_PACK_Office_Office
GEFORCE_40-SERIES_ALUMINUM_COASTER_Lifestyle_Lifestyle
NVIDIA_TWILL_HAT_-_SAGE_Apparel_Mens
WOMENS_FLEECE_CROPPED_CREW_Apparel_Womens
LAPEL_PIN_Lifestyle_Lifestyle
NVIDIA_ICONOGRAPHY_BANDANA_Lifestyle_Lifestyle
HEROES_OF_NVIDIA_3.0_UNISEX_TEE_Apparel_Mens
NIKE_2.0_POLO_WOMENS_Apparel_Womens
IGLOO_COAST_COOLER_Bags_Bags
WOMENS_LOGO_TEE_Apparel_Womens
WOMENS_BEYOND_YOGA_SPACEDYE_RACERBACK_CROPPED_TANK_Apparel_Womens
NVIDIA_CORDUROY_HAT_Apparel_Mens
SWELL_16OZ_PET_BOWL_Lifestyle_Lifestyle
JETSON_NANO_DEVELOPER_KIT_NVIDIA_Electronics_Jetson
NVIDIA_HEX_SLING_BAG_-_GRAY_Bags_Bags
MARINE_LAYER_CORBET_FULL_ZIP_MENS_Apparel_Mens
GEFORCE_RTX_4060_Ti_User_Guide_Rev1
GeForce_RTX_4080_QSG_Rev1
NVIDIA_DUO-TONE_LOGO_UNISEX_TEE_Apparel_Mens
NVIDIA_SHIELD_REMOTE_2020_NVIDIA_Electronics_Shield
TIMBUK2_COPILOT_ROLLER_LUGGAGE_Bags_Bags
COTTON_TOUCH_POLO_WOMENS_Apparel_Womens
NEXT_LEVEL_ECO_UNISEX_TEE_UNISEX_Apparel_Mens

In [10]:
# CM delete all documents
import requests

docs_url = f'http://{IPADDRESS}:{UNSTRUCTURED_DATA_PORT}/documents'
response = requests.get(docs_url)

if response.status_code == 200:
    docs = response.json().get("documents", [])
    for doc in docs:
        delete_url = f'http://{IPADDRESS}:{UNSTRUCTURED_DATA_PORT}/documents'
        delete_resp = requests.delete(delete_url, params={"filename": doc})
        if delete_resp.status_code == 200:
            print(f"Deleted {doc}")
        else:
            print(f"Failed to delete {doc}. Error:", delete_resp.status_code, delete_resp.text)
else:
    print("Failed to get documents for deletion. Error:", response.status_code, response.text)

Deleted GEFORCE_TRIANGULATION_TEE_UNISEX_Apparel_Mens
Deleted FULL_ZIP_NEURAL_HOODIE_UNISEX_Apparel_Mens
Deleted TROIKA_CONSTRUCTION_PEN_Office_Office
Deleted NVIDIA_JETSON_ORIN_NANO_DEVELOPER_KIT_NVIDIA_Electronics_Jetson
Deleted NORTH_FACE_MENS_TREKKER_JACKET_Apparel_Mens
Deleted INTENSITY_CLIC_GEL_PEN_Office_Office
Deleted TIMBUK2_VAPOR_BACKPACK_TOTE_-_GRAPHITE_Bags_Bags
Deleted MENS_BEYOND_YOGA_TAKE_IT_EASY_PANT_-_DARKEST_NIGHT_Apparel_Mens
Deleted NVIDIA_SMALL_INFINITY_MOUSEPAD_Office_Office
Deleted FLUX_BONDED_JACKET_WOMENS_LIGHT_HEATHER_Apparel_Womens
Deleted NVIDIA_GEFORCE_RTX_4090_NVIDIA_Electronics_Geforce
Deleted MENS_BEYOND_YOGA_TAKE_IT_EASY_SHORTS_Apparel_Mens
Deleted NVIDIA_SHIELD_TV_PRO_2019_NVIDIA_Electronics_Shield
Deleted GEFORCE_RTX_4070_SUPER_User_Guide_Rev1
Deleted VICTORINOX_LAPTOP_WOMENS_TOTE_Bags_Bags
Deleted CHAMPION_REVERSE_WEAVE_CREWNECK_UNISEX_Apparel_Mens
Deleted 25_OZ._NVIDIA_ICONOGRAPHY_BOTTLE_Drinkware_Drinkware
Deleted PRODIR_PATTERN_PEN_Office_Office
Deleted AUTONOMOUS_TIME_TRAVELER_TEE_UNISEX_Apparel_Mens
Deleted NVIDIA_GEFORCE_RTX_4070_SUPER_NVIDIA_Electronics_Geforce
Deleted 14_OZ._A_NEW_BREED_OF_INNOVATION_MUG_Drinkware_Drinkware
Deleted LONG_SLEEVE_PERFORMANCE_SHIRT_WOMENS_Apparel_Womens
Deleted NVIDIA_GREEN_LABEL_BEANIE_Apparel_Mens
Deleted OGIO_STRATAGEM_BACKPACK_Bags_Bags
Deleted physics
Deleted GIFT_BAG_Bags_Bags
Deleted GEFORCE_LOGO_HIGH_DENSITY_TEE_UNISEX_Apparel_Mens
Deleted NVIDIA_ATHLETIC_CREW_SOCKS_Apparel_Mens
Deleted 14_OZ._I_AM_AI_MUG_Drinkware_Drinkware
Deleted OGIO_CATALYST_DUFFEL_-_BLACK_Bags_Bags
Deleted WOMENS_BEYOND_YOGA_MOVEMENT_SKIRT_Apparel_Womens
Deleted LONG_SLEEVE_PERFORMANCE_SHIRT_MENS_Apparel_Mens
Deleted GEFORCE_NOW_50_MEMBERSHIP_GIFT_CARD_NVIDIA_Electronics_Geforce
Deleted NVIDIA_GEFORCE_RTX_4080_NVIDIA_Electronics_Geforce
Deleted WOMENS_BEYOND_YOGA_REFOCUS_TANK_Apparel_Womens
Deleted UNISEX_TMYBTMYS_CUDA_TEE_Apparel_Mens
Deleted NORTH_FACE_WOMENS_TREKKER_JACKET_Apparel_Womens
Deleted WOMENS_BEYOND_YOGA_IN-STRIDE_PULLOVER_-_BLACK_Apparel_Womens
Deleted FLUX_BONDED_JACKET_2.0_MENS_LIGHT_HEATHER_Apparel_Mens
Deleted NVIDIA_FLOW_LARGE_MOUSEPAD_Office_Office
Deleted MENS_LOGO_TEE_Apparel_Mens
Deleted MARINE_LAYER_CORBET_FULL_ZIP_VEST_MENS_Apparel_Mens
Deleted COMPUTER_CARE_KIT_Office_Office
Deleted 20_OZ._ELEMENTAL_WATER_BOTTLE_Drinkware_Drinkware
Deleted TOPO_ROVER_TECH_PACK_Bags_Bags
Deleted NVIDIA_NIMBLE_CHAMP_PRO_CHARGER_Lifestyle_Lifestyle
Deleted WIREFRAME_EYE_GRAPHIC_TEE_UNISEX_Apparel_Mens
Deleted NVIDIA_LIGHTWEIGHT_HOODIE_Apparel_Mens
Deleted TOTE_BAG_Bags_Bags
Deleted NIKE_2.0_POLO_MENS_Apparel_Mens
Deleted MENS_LULULEMON_ABC_JOGGER_Apparel_Mens
Deleted COTTON_TOUCH_POLO_MENS_Apparel_Mens
Deleted GEFORCE_RTX_4080_SUPER_User_Guide_Rev1
Deleted MENS_BEYOND_YOGA_CREW_T-SHIRT_-_DARKEST_NIGHT_Apparel_Mens
Deleted PORTABLE_FOLDING_CHAIR_Lifestyle_Lifestyle
Deleted NVIDIA_GEFORCE_HAT_Apparel_Mens
Deleted NVIDIA_GEFORCE_RTX_4060TI_8GB_NVIDIA_Electronics_Geforce
Deleted WOMENS_POCKET_LEGGINGS_Apparel_Womens
Deleted cs
Deleted 32_OZ._NVIDIA_ICONOGRAPHY_BOTTLE_Drinkware_Drinkware
Deleted TIMBUK2_LAPTOP_SLEEVE_-_2_SIZES_Office_Office
Deleted 14_OZ._NVIDIA_LOGO_MUG_Drinkware_Drinkware
Deleted NVIDIA_SHIELD_TV_2019_NVIDIA_Electronics_Shield
Deleted NVIDIA_LICENSE_PLATE_FRAME_Lifestyle_Lifestyle
Deleted UNISEX_INSPIRE_365_TEE_Apparel_Mens
Deleted CLUBMAN_SUNGLASSES_Lifestyle_Lifestyle
Deleted TITLEIST_PRO_V1_HALF_DOZEN_GOLF_BALLS_Lifestyle_Lifestyle
Deleted 40_OZ._STANLEY_QUENCHER_TUMBLER_Drinkware_Drinkware
Deleted 14_OZ._VISUAL_PURR-CEPTION_MUG_Drinkware_Drinkware
Deleted ANKLE_SOCK_UNISEX_Apparel_Mens
Deleted WOMENS_V-NECK_TEE_Apparel_Womens
Deleted RULER_Office_Office
Deleted RULER_2.0_Office_Office
Deleted I_AM_AI_TEE_MENS_Apparel_Mens
Deleted GEFORCE_ABSTRACTION_TEE_UNISEX_Apparel_Mens
Deleted FAQ
Deleted NVIDIA_GEFORCE_RTX_4070_NVIDIA_Electronics_Geforce
Deleted GeForce_RTX_4090_QSG_Rev1
Deleted GeForce_RTX_4070_QSG_Rev1
Deleted I_AM_AI_TEE_WOMENS_Apparel_Womens
Deleted MARINE_LAYER_CORBET_FULL_ZIP_VEST_WOMENS_Apparel_Womens
Deleted 12_MARLED_KNIT_CUFF_BEANIE_Apparel_Mens
Deleted YOUTH_LOGO_TEE_Apparel_Kids
Deleted TIMBUK2_LAPTOP_SLEEVE_-_2_SIZES_Bags_Bags
Deleted math
Deleted TIMBUK2_PARKSIDE_BACKPACK_2.0_Bags_Bags
Deleted NVIDIA_ICONOGRAPHY_KRAFT_POCKET_JOURNAL_-3_PACK_Office_Office
Deleted GEFORCE_40-SERIES_ALUMINUM_COASTER_Lifestyle_Lifestyle
Deleted NVIDIA_TWILL_HAT_-_SAGE_Apparel_Mens
Deleted WOMENS_FLEECE_CROPPED_CREW_Apparel_Womens
Deleted LAPEL_PIN_Lifestyle_Lifestyle
Deleted NVIDIA_ICONOGRAPHY_BANDANA_Lifestyle_Lifestyle
Deleted HEROES_OF_NVIDIA_3.0_UNISEX_TEE_Apparel_Mens
Deleted NIKE_2.0_POLO_WOMENS_Apparel_Womens
Deleted IGLOO_COAST_COOLER_Bags_Bags
Deleted WOMENS_LOGO_TEE_Apparel_Womens
Deleted WOMENS_BEYOND_YOGA_SPACEDYE_RACERBACK_CROPPED_TANK_Apparel_Womens
Deleted NVIDIA_CORDUROY_HAT_Apparel_Mens
Deleted SWELL_16OZ_PET_BOWL_Lifestyle_Lifestyle
Deleted JETSON_NANO_DEVELOPER_KIT_NVIDIA_Electronics_Jetson
Deleted NVIDIA_HEX_SLING_BAG_-_GRAY_Bags_Bags
Deleted MARINE_LAYER_CORBET_FULL_ZIP_MENS_Apparel_Mens
Deleted GEFORCE_RTX_4060_Ti_User_Guide_Rev1
Deleted GeForce_RTX_4080_QSG_Rev1
Deleted NVIDIA_DUO-TONE_LOGO_UNISEX_TEE_Apparel_Mens
Deleted NVIDIA_SHIELD_REMOTE_2020_NVIDIA_Electronics_Shield
Deleted TIMBUK2_COPILOT_ROLLER_LUGGAGE_Bags_Bags
Deleted COTTON_TOUCH_POLO_WOMENS_Apparel_Womens
Deleted NEXT_LEVEL_ECO_UNISEX_TEE_UNISEX_Apparel_Mens

In [2]:
import requests

url = f'http://{IPADDRESS}:{UNSTRUCTURED_DATA_PORT}/health'
print(url)
headers = {
    'accept': 'application/json'
}

response = requests.get(url, headers=headers)

# Print the response
print(response.status_code)
print(response.json())

http://localhost:8086/health
200
{'message': 'Service is up.'}

#### Ingest Syllabus (txt)

In [11]:
# Ingest syllabus
import requests
import os
# URL of the API endpoint
url = f'http://{IPADDRESS}:{UNSTRUCTURED_DATA_PORT}/documents'
# Path to the PDF file you want to upload
directory_path = '../data/course_syllabus'

# Loop through all files in the directory
for filename in os.listdir(directory_path):
    # Check if the file is a PDF
    if filename.endswith('.txt'):
        file_path = os.path.join(directory_path, filename)

        # Open the file in binary mode and send it in a POST request
        with open(file_path, 'rb') as file:
            files = {'file': file}
            response = requests.post(url, files=files)

        # Print the response from the server
        print(f'Uploaded {filename}: {response.status_code}')
        print(response.json())

Uploaded math.txt: 200
{'message': 'File uploaded successfully'}
Uploaded cs.txt: 200
{'message': 'File uploaded successfully'}
Uploaded physics.txt: 200
{'message': 'File uploaded successfully'}

#### Get the list of documents

In [12]:
import requests

# URL of the API endpoint
url = f'http://{IPADDRESS}:{UNSTRUCTURED_DATA_PORT}/documents'

# Send the GET request
response = requests.get(url)

# Print the response from the server
print(f'Response Status Code: {response.status_code}')
#print(response.json())

# Check if the request was successful
if response.status_code == 200:
    data = response.json()
    documents = data.get('documents', [])

    # Format and print the list of documents
    print("Available Documents:")
    for idx, document in enumerate(documents, start=1):
        print(f"{idx}. {document}")
else:
    print(f"Failed to retrieve documents. Status Code: {response.status_code}")

Response Status Code: 200
Available Documents:
1. physics
2. cs
3. math

#### (For reference) Delete a document

The cell is in "raw" and does not execute. This code is for reference alone.

import requests

# URL of the API endpoint
url = f'http://{IPADDRESS}:{UNSTRUCTURED_DATA_PORT}/documents'

# Filename of the document to delete
filename = 'GEFORCE_RTX_4070_SUPER_User_Guide_Rev1'

# Parameters to be sent with the DELETE request
params = {'filename': filename}

# Send the DELETE request
response = requests.delete(url, params=params)

# Print the response from the server
print(f'Response Status Code: {response.status_code}')
print(response.json())

### Ingest data into a postgres db

In [21]:
# CM Read and print classroom data to ensure it has been populated
import psycopg2

# Database connection parameters
db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',  # Adjust if needed
    'port': '5432'
}

# Connect to the database
conn = psycopg2.connect(**db_params)
cur = conn.cursor()

# List of tables to check
tables = [
    "students", "instructors", "courses", "course_instructors", 
    "enrollments", "assignments", "assignment_grades", "exams",
    "exam_grades", "lectures", "lecture_materials", "discussion_boards", 
    "posts"
]

# We'll just fetch first 5 rows for demonstration
for table in tables:
    print(f"\n=== Table: {table} ===")
    query = f"SELECT * FROM {table} LIMIT 5;"
    cur.execute(query)
    rows = cur.fetchall()
    if rows:
        colnames = [desc[0] for desc in cur.description]
        # Print headers
        print(" | ".join(colnames))
        # Print rows
        for row in rows:
            print(" | ".join(str(r) for r in row))
    else:
        print("No data found.")

cur.close()
conn.close()

=== Table: students ===
student_id | first_name | last_name | email | major | enrollment_year
1 | Alice | Smith | alice.smith@example.com | Computer Science | 2022
2 | Bob | Johnson | bob.johnson@example.com | Mathematics | 2021
3 | Charlie | Lee | charlie.lee@example.com | Literature | 2023
4 | Diana | Martinez | diana.martinez@example.com | Physics | 2022
5 | Ethan | Garcia | ethan.garcia@example.com | Engineering | 2022

=== Table: instructors ===
instructor_id | first_name | last_name | email | department
1 | John | Williams | john.williams@example.com | Computer Science
2 | Mary | Davis | mary.davis@example.com | Mathematics

=== Table: courses ===
course_id | course_code | title | description | semester | credits
1 | CS101 | Intro to Computer Science | A beginner course in CS | Fall 2024 | 4
2 | MATH201 | Advanced Calculus | In-depth calculus for math majors | Fall 2024 | 3

=== Table: course_instructors ===
course_instructor_id | course_id | instructor_id
1 | 1 | 1
2 | 2 | 2

=== Table: enrollments ===
enrollment_id | student_id | course_id | role | enrolled_on
1 | 1 | 1 | student | 2024-08-20
2 | 2 | 1 | student | 2024-08-20
3 | 3 | 1 | student | 2024-08-20
4 | 4 | 2 | student | 2024-08-20
5 | 5 | 2 | student | 2024-08-20

=== Table: assignments ===
assignment_id | course_id | title | description | due_date | max_points
1 | 1 | Homework 1 | Basic Python exercises | 2024-09-15 23:59:00 | 100
2 | 2 | Problem Set 1 | Integration problems | 2024-09-18 23:59:00 | 100

=== Table: assignment_grades ===
assignment_grade_id | assignment_id | student_id | grade | feedback | graded_on
1 | 1 | 1 | 95.00 | Great job! | 2024-09-16 12:00:00
2 | 1 | 2 | 88.50 | Good effort | 2024-09-16 12:00:00
3 | 1 | 3 | 72.00 | Needs improvement | 2024-09-16 12:00:00
4 | 2 | 4 | 91.00 | Well done! | 2024-09-19 10:00:00
5 | 2 | 5 | 85.00 | Nice work | 2024-09-19 10:00:00

=== Table: exams ===
exam_id | course_id | title | exam_date | max_points
1 | 1 | Midterm Exam | 2024-10-10 10:00:00 | 100
2 | 2 | Midterm Exam | 2024-10-12 10:00:00 | 100

=== Table: exam_grades ===
exam_grade_id | exam_id | student_id | grade | feedback | graded_on
1 | 1 | 1 | 89.00 | Solid understanding | 2024-10-11 15:00:00
2 | 1 | 2 | 93.00 | Excellent | 2024-10-11 15:00:00
3 | 1 | 3 | 70.00 | Study more | 2024-10-11 15:00:00
4 | 2 | 4 | 88.00 | Good job | 2024-10-13 09:00:00
5 | 2 | 5 | 82.00 | Keep practicing | 2024-10-13 09:00:00

=== Table: lectures ===
lecture_id | course_id | title | lecture_date | description
1 | 1 | Introduction to CS | 2024-08-25 09:00:00 | Overview of computer science.
2 | 2 | Limits and Continuity | 2024-08-25 09:00:00 | Reviewing limits in calculus.

=== Table: lecture_materials ===
material_id | lecture_id | title | material_type | url | description
1 | 1 | Week1 Slides | slides | http://example.com/cs101_week1_slides.pdf | Lecture slides for week 1
2 | 2 | Limits Reading | reading | http://example.com/math201_limits.pdf | Reading material on limits

=== Table: discussion_boards ===
board_id | course_id | title | description
1 | 1 | CS101 Discussion | General discussion for CS101
2 | 2 | MATH201 Discussion | General discussion for MATH201

=== Table: posts ===
post_id | board_id | author_type | author_id | content | posted_at | parent_post_id
1 | 1 | student | 1 | I'm really enjoying this class! | 2024-08-26 10:00:00 | None
2 | 1 | student | 2 | Can someone help me with the homework? | 2024-08-26 11:00:00 | None
3 | 2 | student | 4 | Calculus is challenging but fun. | 2024-08-27 09:30:00 | None
4 | 2 | instructor | 2 | Feel free to ask questions anytime! | 2024-08-27 10:00:00 | 3

In [23]:
# CM inspect again for debug vanna generated FROM public.customer_data
import psycopg2
import psycopg2.extras

# Database connection parameters
db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',  # or your db host
    'port': '5432'
}

# Connect to the database
conn = psycopg2.connect(**db_params)
cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

# Query to list all tables in the public schema
cur.execute("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;
""")

tables = cur.fetchall()

print("Tables in 'public' schema of 'customer_data' database:")
for t in tables:
    print("-", t["table_name"])

# For each table, list its columns
for t in tables:
    table_name = t["table_name"]
    print(f"\nColumns in {table_name}:")
    cur.execute(f"""
    SELECT column_name, data_type, is_nullable
    FROM information_schema.columns
    WHERE table_name = %s
    ORDER BY ordinal_position;
    """, (table_name,))
    columns = cur.fetchall()
    for c in columns:
        print(f"- {c['column_name']} ({c['data_type']}, nullable: {c['is_nullable']})")

cur.close()
conn.close()

Tables in 'public' schema of 'customer_data' database:
- assignment_grades
- assignments
- course_instructors
- courses
- discussion_boards
- enrollments
- exam_grades
- exams
- instructors
- lecture_materials
- lectures
- posts
- students

Columns in assignment_grades:
- assignment_grade_id (integer, nullable: NO)
- assignment_id (integer, nullable: YES)
- student_id (integer, nullable: YES)
- grade (numeric, nullable: YES)
- feedback (text, nullable: YES)
- graded_on (timestamp without time zone, nullable: YES)

Columns in assignments:
- assignment_id (integer, nullable: NO)
- course_id (integer, nullable: YES)
- title (character varying, nullable: YES)
- description (text, nullable: YES)
- due_date (timestamp without time zone, nullable: YES)
- max_points (integer, nullable: YES)

Columns in course_instructors:
- course_instructor_id (integer, nullable: NO)
- course_id (integer, nullable: YES)
- instructor_id (integer, nullable: YES)

Columns in courses:
- course_id (integer, nullable: NO)
- course_code (character varying, nullable: YES)
- title (character varying, nullable: YES)
- description (text, nullable: YES)
- semester (character varying, nullable: YES)
- credits (integer, nullable: YES)

Columns in discussion_boards:
- board_id (integer, nullable: NO)
- course_id (integer, nullable: YES)
- title (character varying, nullable: YES)
- description (text, nullable: YES)

Columns in enrollments:
- enrollment_id (integer, nullable: NO)
- student_id (integer, nullable: YES)
- course_id (integer, nullable: YES)
- role (character varying, nullable: YES)
- enrolled_on (date, nullable: YES)

Columns in exam_grades:
- exam_grade_id (integer, nullable: NO)
- exam_id (integer, nullable: YES)
- student_id (integer, nullable: YES)
- grade (numeric, nullable: YES)
- feedback (text, nullable: YES)
- graded_on (timestamp without time zone, nullable: YES)

Columns in exams:
- exam_id (integer, nullable: NO)
- course_id (integer, nullable: YES)
- title (character varying, nullable: YES)
- exam_date (timestamp without time zone, nullable: YES)
- max_points (integer, nullable: YES)

Columns in instructors:
- instructor_id (integer, nullable: NO)
- first_name (character varying, nullable: YES)
- last_name (character varying, nullable: YES)
- email (character varying, nullable: YES)
- department (character varying, nullable: YES)

Columns in lecture_materials:
- material_id (integer, nullable: NO)
- lecture_id (integer, nullable: YES)
- title (character varying, nullable: YES)
- material_type (character varying, nullable: YES)
- url (text, nullable: YES)
- description (text, nullable: YES)

Columns in lectures:
- lecture_id (integer, nullable: NO)
- course_id (integer, nullable: YES)
- title (character varying, nullable: YES)
- lecture_date (timestamp without time zone, nullable: YES)
- description (text, nullable: YES)

Columns in posts:
- post_id (integer, nullable: NO)
- board_id (integer, nullable: YES)
- author_type (character varying, nullable: YES)
- author_id (integer, nullable: YES)
- content (text, nullable: YES)
- posted_at (timestamp without time zone, nullable: YES)
- parent_post_id (integer, nullable: YES)

Columns in students:
- student_id (integer, nullable: NO)
- first_name (character varying, nullable: YES)
- last_name (character varying, nullable: YES)
- email (character varying, nullable: YES)
- major (character varying, nullable: YES)
- enrollment_year (integer, nullable: YES)

In [24]:
import psycopg2

# Database connection parameters
db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',  # or your db host
    'port': '5432'
}

conn = psycopg2.connect(**db_params)
cur = conn.cursor()

# Drop tables if they exist
drop_statements = [
    "DROP TABLE IF EXISTS posts CASCADE",
    "DROP TABLE IF EXISTS discussion_boards CASCADE",
    "DROP TABLE IF EXISTS lecture_materials CASCADE",
    "DROP TABLE IF EXISTS lectures CASCADE",
    "DROP TABLE IF EXISTS exam_grades CASCADE",
    "DROP TABLE IF EXISTS exams CASCADE",
    "DROP TABLE IF EXISTS assignment_grades CASCADE",
    "DROP TABLE IF EXISTS assignments CASCADE",
    "DROP TABLE IF EXISTS enrollments CASCADE",
    "DROP TABLE IF EXISTS course_instructors CASCADE",
    "DROP TABLE IF EXISTS courses CASCADE",
    "DROP TABLE IF EXISTS instructors CASCADE",
    "DROP TABLE IF EXISTS students CASCADE"
]

for stmt in drop_statements:
    cur.execute(stmt)

conn.commit()
cur.close()
conn.close()

print("All tables dropped successfully!")

All tables dropped successfully!

In [25]:
import psycopg2

# Database connection parameters
db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',  # or your db host
    'port': '5432'
}

conn = psycopg2.connect(**db_params)
cur = conn.cursor()

# Drop the mega_table if it exists
cur.execute("DROP TABLE IF EXISTS mega_table CASCADE;")
conn.commit()

# Create a single mega_table
# We'll include a wide range of columns from all entities. 
# Adjust types and sizes as needed.
create_mega_table = """
CREATE TABLE mega_table (
    student_id INT,
    student_first_name VARCHAR(50),
    student_last_name VARCHAR(50),
    student_email VARCHAR(100),
    student_major VARCHAR(100),
    student_enrollment_year INT,

    course_id INT,
    course_code VARCHAR(50),
    course_title VARCHAR(255),
    course_description TEXT,
    course_semester VARCHAR(50),
    course_credits INT,

    instructor_id INT,
    instructor_first_name VARCHAR(50),
    instructor_last_name VARCHAR(50),
    instructor_email VARCHAR(100),
    instructor_department VARCHAR(100),

    assignment_id INT,
    assignment_title VARCHAR(255),
    assignment_description TEXT,
    assignment_due_date TIMESTAMP,
    assignment_max_points INT,
    assignment_grade DECIMAL(5,2),
    assignment_feedback TEXT,
    assignment_graded_on TIMESTAMP,

    exam_id INT,
    exam_title VARCHAR(255),
    exam_date TIMESTAMP,
    exam_max_points INT,
    exam_grade DECIMAL(5,2),
    exam_feedback TEXT,
    exam_graded_on TIMESTAMP,

    lecture_id INT,
    lecture_title VARCHAR(255),
    lecture_date TIMESTAMP,
    lecture_description TEXT,

    material_id INT,
    material_title VARCHAR(255),
    material_type VARCHAR(50),
    material_url TEXT,
    material_description TEXT,

    board_id INT,
    board_title VARCHAR(255),
    board_description TEXT,

    post_id INT,
    post_author_type VARCHAR(50),
    post_author_id INT,
    post_content TEXT,
    post_posted_at TIMESTAMP,
    post_parent_post_id INT
);
"""

cur.execute(create_mega_table)
conn.commit()

cur.close()
conn.close()

print("Single mega_table created successfully!")

Single mega_table created successfully!

In [19]:
import csv
import psycopg2
import os

# Database connection parameters (adjust as necessary)
db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',  # or your db host
    'port': '5432'
}

# Connect to the database
conn = psycopg2.connect(**db_params)
cur = conn.cursor()

# Drop existing tables if they exist
cur.execute("DROP TABLE IF EXISTS homework CASCADE;")
cur.execute("DROP TABLE IF EXISTS students CASCADE;")
conn.commit()

# Create the `students` table
cur.execute("""
    CREATE TABLE students (
        student_id SERIAL PRIMARY KEY,
        first_name VARCHAR(50),
        last_name VARCHAR(50),
        email VARCHAR(100),
        major VARCHAR(100),
        enrollment_year INT
    );
""")

# Create the `homework` table
cur.execute("""
    CREATE TABLE homework (
        hw_id SERIAL PRIMARY KEY,
        hw_name VARCHAR(255),
        hw_content TEXT,
        due_date DATE,
        grade INT,
        course_name VARCHAR(255),
        student_id INT REFERENCES students(student_id)
    );
""")
conn.commit()

# Create a data directory if it doesn't exist
data_dir = 'data'
if not os.path.exists(data_dir):
    os.makedirs(data_dir)

# Generate synthetic data for `students`
students_data = [
    [1, "Alice", "Smith", "alice.smith@example.com", "Computer Science", 2022],
    [2, "Bob", "Johnson", "bob.johnson@example.com", "Mathematics", 2021],
    [3, "Charlie", "Lee", "charlie.lee@example.com", "Literature", 2023],
    [4, "Diana", "Martinez", "diana.martinez@example.com", "Physics", 2022]
]

# Generate synthetic data for `homework`
homework_data = [
    [1, "Homework 1", "Solve problems 1 to 10 from the textbook.", "2024-09-15", 90, "Intro to Programming", 1],
    [2, "Homework 2", "Write an essay on the history of computing.", "2024-09-25", None, "Intro to Programming", 1],
    [3, "Quiz 1", "Answer 10 multiple-choice questions on calculus.", "2024-09-18", 85, "Calculus I", 2],
    [4, "Essay 1", "Discuss the themes in 'To Kill a Mockingbird'.", "2024-10-01", None, "Literature Studies", 3],
    [5, "Lab Report 1", "Analyze the results of the pendulum experiment.", "2024-09-20", 88, "Physics 101", 4],
    [6, "Midterm Practice", "Review all chapters covered in class.", "2024-10-10", None, "Physics 101", 4],
    [7, "Research Proposal", "Propose a topic for the final research paper.", "2024-10-15", None, "Advanced Mathematics", 1],
    [8, "Programming Assignment", "Build a basic calculator using Python.", "2024-09-28", 95, "Intro to Programming", 2],
    [9, "Short Story Analysis", "Analyze a short story of your choice.", "2024-10-05", None, "Literature Studies", 3],
    [10, "Experiment Analysis", "Explain the findings of the electric circuit lab.", "2024-09-25", 92, "Physics 101", 4]
]

# Helper function to write CSV files
def write_csv(filename, headers, data):
    with open(filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        writer.writerows(data)

# Write data to CSV files
write_csv(os.path.join(data_dir, 'students.csv'),
          ["student_id", "first_name", "last_name", "email", "major", "enrollment_year"],
          students_data)

write_csv(os.path.join(data_dir, 'homework.csv'),
          ["hw_id", "hw_name", "hw_content", "due_date", "grade", "course_name", "student_id"],
          homework_data)

# Helper function to load CSV data into a table
def load_csv_into_table(conn, table_name, csv_file, columns):
    with open(csv_file, 'r', encoding='utf-8') as f:
        next(f)  # Skip header line
        cur = conn.cursor()
        copy_sql = f"COPY {table_name} ({', '.join(columns)}) FROM STDIN WITH CSV"
        cur.copy_expert(copy_sql, f)
        conn.commit()

# Load data into the `students` table
load_csv_into_table(conn, "students", os.path.join(data_dir, "students.csv"),
                    ["student_id", "first_name", "last_name", "email", "major", "enrollment_year"])

# Load data into the `homework` table
load_csv_into_table(conn, "homework", os.path.join(data_dir, "homework.csv"),
                    ["hw_id", "hw_name", "hw_content", "due_date", "grade", "course_name", "student_id"])

print("Tables `students` and `homework` created and populated with synthetic data successfully!")

cur.close()
conn.close()

Tables `students` and `homework` created and populated with synthetic data successfully!

In [21]:
# print all tables
import psycopg2
from tabulate import tabulate

db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',  
    'port': '5432'
}

conn = psycopg2.connect(**db_params)
cur = conn.cursor()

def print_all_tables(cur):
    # Get all table names
    cur.execute("""
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public';
    """)
    tables = cur.fetchall()

    for (table_name,) in tables:
        # Get column names 
        cur.execute(f"""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s 
            ORDER BY ordinal_position;
        """, (table_name,))
        columns = [col[0] for col in cur.fetchall()]

        # If the table has no columns, skip it
        if not columns:
            continue

        # Get all rows 
        cur.execute(f"SELECT * FROM {table_name};")
        rows = cur.fetchall()

        # Print table name and content
        print(f"\n{table_name.upper()} TABLE:")
        print(tabulate(rows, headers=columns, tablefmt='psql'))

print_all_tables(cur)
cur.close()
conn.close()

STUDENTS TABLE:
+--------------+--------------+-------------+----------------------------+------------------+-------------------+
|   student_id | first_name   | last_name   | email                      | major            |   enrollment_year |
|--------------+--------------+-------------+----------------------------+------------------+-------------------|
|            1 | Alice        | Smith       | alice.smith@example.com    | Computer Science |              2022 |
|            2 | Bob          | Johnson     | bob.johnson@example.com    | Mathematics      |              2021 |
|            3 | Charlie      | Lee         | charlie.lee@example.com    | Literature       |              2023 |
|            4 | Diana        | Martinez    | diana.martinez@example.com | Physics          |              2022 |
+--------------+--------------+-------------+----------------------------+------------------+-------------------+

HOMEWORK TABLE:
+---------+------------------------+---------------------------------------------------+------------+---------+----------------------+--------------+
|   hw_id | hw_name                | hw_content                                        | due_date   |   grade | course_name          |   student_id |
|---------+------------------------+---------------------------------------------------+------------+---------+----------------------+--------------|
|       1 | Homework 1             | Solve problems 1 to 10 from the textbook.         | 2024-09-15 |      90 | Intro to Programming |            1 |
|       2 | Homework 2             | Write an essay on the history of computing.       | 2024-09-25 |         | Intro to Programming |            1 |
|       3 | Quiz 1                 | Answer 10 multiple-choice questions on calculus.  | 2024-09-18 |      85 | Calculus I           |            2 |
|       4 | Essay 1                | Discuss the themes in 'To Kill a Mockingbird'.    | 2024-10-01 |         | Literature Studies   |            3 |
|       5 | Lab Report 1           | Analyze the results of the pendulum experiment.   | 2024-09-20 |      88 | Physics 101          |            4 |
|       6 | Midterm Practice       | Review all chapters covered in class.             | 2024-10-10 |         | Physics 101          |            4 |
|       7 | Research Proposal      | Propose a topic for the final research paper.     | 2024-10-15 |         | Advanced Mathematics |            1 |
|       8 | Programming Assignment | Build a basic calculator using Python.            | 2024-09-28 |      95 | Intro to Programming |            2 |
|       9 | Short Story Analysis   | Analyze a short story of your choice.             | 2024-10-05 |         | Literature Studies   |            3 |
|      10 | Experiment Analysis    | Explain the findings of the electric circuit lab. | 2024-09-25 |      92 | Physics 101          |            4 |
+---------+------------------------+---------------------------------------------------+------------+---------+----------------------+--------------+

In [5]:
import psycopg2
from tabulate import tabulate

# Database connection parameters (ensure these match your environment)
db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost', # or your db host
    'port': '5432'
}

# Connect to the database
conn = psycopg2.connect(**db_params)
cur = conn.cursor()

# Function to print table contents in a nice format
def print_table(cur, table_name):
    # Construct and execute the query
    query = f"SELECT * FROM {table_name};"
    cur.execute(query)
    rows = cur.fetchall()
    
    # Get column names
    columns = [desc[0] for desc in cur.description]
    
    # Print using tabulate
    print(f"\n{table_name.upper()} TABLE:")
    print(tabulate(rows, headers=columns, tablefmt='psql'))

# Get all table names in the database
cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';")
tables = [table[0] for table in cur.fetchall()]

# Print each table
for table in tables:
    print_table(cur, table)

# Clean up
cur.close()
conn.close()

INSTRUCTORS TABLE:
+-----------------+--------------+-------------+---------------------------+------------------+
|   instructor_id | first_name   | last_name   | email                     | department       |
|-----------------+--------------+-------------+---------------------------+------------------|
|               1 | John         | Williams    | john.williams@example.com | Computer Science |
|               2 | Mary         | Davis       | mary.davis@example.com    | Mathematics      |
+-----------------+--------------+-------------+---------------------------+------------------+

STUDENTS TABLE:
+--------------+--------------+-------------+----------------------------+------------------+-------------------+
|   student_id | first_name   | last_name   | email                      | major            |   enrollment_year |
|--------------+--------------+-------------+----------------------------+------------------+-------------------|
|            1 | Alice        | Smith       | alice.smith@example.com    | Computer Science |              2022 |
|            2 | Bob          | Johnson     | bob.johnson@example.com    | Mathematics      |              2021 |
|            3 | Charlie      | Lee         | charlie.lee@example.com    | Literature       |              2023 |
|            4 | Diana        | Martinez    | diana.martinez@example.com | Physics          |              2022 |
+--------------+--------------+-------------+----------------------------+------------------+-------------------+

ENROLLMENTS TABLE:
+-----------------+--------------+-------------+---------+---------------+
|   enrollment_id |   student_id |   course_id | role    | enrolled_on   |
|-----------------+--------------+-------------+---------+---------------|
|               1 |            1 |           1 | student | 2024-08-20    |
|               2 |            2 |           1 | student | 2024-08-20    |
|               3 |            3 |           3 | student | 2025-01-15    |
|               4 |            4 |           2 | student | 2024-08-20    |
|               5 |            1 |           2 | TA      | 2024-08-22    |
+-----------------+--------------+-------------+---------+---------------+

COURSES TABLE:
+-------------+---------------+---------------------------+-------------+
|   course_id | course_code   | title                     | semester    |
|-------------+---------------+---------------------------+-------------|
|           1 | CS101         | Intro to Computer Science | Fall 2024   |
|           2 | MATH201       | Advanced Calculus         | Fall 2024   |
|           3 | LIT301        | Modern Literature         | Spring 2025 |
+-------------+---------------+---------------------------+-------------+

In [4]:
!pip install psycopg2-binary

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.10/dist-packages (2.9.10)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 24.1.2 -> 24.3.1
[notice] To update, run: python -m pip install --upgrade pip

In [14]:
# delete all tables
import psycopg2

# Database connection parameters (ensure these match your environment)
db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',  # or your db host
    'port': '5432'
}

try:
    # Connect to the database
    conn = psycopg2.connect(**db_params)
    conn.autocommit = True  # Enable autocommit for dropping tables
    cur = conn.cursor()
    
    # Fetch all table names in the 'public' schema
    cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';")
    tables = [table[0] for table in cur.fetchall()]
    
    # Drop each table
    for table in tables:
        print(f"Dropping table: {table}")
        cur.execute(f"DROP TABLE IF EXISTS {table} CASCADE;")  # CASCADE to handle dependencies

    print("All tables have been dropped successfully.")

except Exception as e:
    print(f"An error occurred: {e}")
finally:
    # Clean up
    if 'cur' in locals():
        cur.close()
    if 'conn' in locals():
        conn.close()

Dropping table: instructors
Dropping table: students
Dropping table: enrollments
Dropping table: courses
All tables have been dropped successfully.

In [15]:
# list all tables
import psycopg2
from tabulate import tabulate

# Database connection parameters (ensure these match your environment)
db_params = {
    'dbname': 'customer_data',
    'user': 'postgres',
    'password': 'password',
    'host': 'localhost',  # or your db host
    'port': '5432'
}

try:
    # Connect to the database
    conn = psycopg2.connect(**db_params)
    cur = conn.cursor()
    
    # Query to fetch all table names in the 'public' schema
    cur.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';")
    tables = cur.fetchall()
    
    # Display the list of tables
    if tables:
        print("\nList of tables in the database:")
        print(tabulate(tables, headers=["Table Name"], tablefmt="psql"))
    else:
        print("No tables found in the database.")
        
except Exception as e:
    print(f"An error occurred: {e}")
finally:
    # Clean up
    if 'cur' in locals():
        cur.close()
    if 'conn' in locals():
        conn.close()

No tables found in the database.

In [23]:
import psycopg2

# Database connection parameters
db_params = {
    'dbname': 'customer_data',  # Replace with your actual database name
    'user': 'postgres',
    'password': 'password',  # Replace with your password
    'host': 'localhost',  # Adjust if needed
    'port': '5432'
}

# Connect to the database
conn = psycopg2.connect(**db_params)
cur = conn.cursor()

# List all tables in the public schema
print("\n=== List of Tables ===")
cur.execute("""
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_schema = 'public';
""")
tables = cur.fetchall()
for table in tables:
    print(table[0])

cur.close()
conn.close()

=== List of Tables ===
students
homework

In [25]:
# Reconnect to the database
conn = psycopg2.connect(**db_params)
cur = conn.cursor()

# Check views that use tables
print("\n=== Views Using Tables ===")
cur.execute("""
    SELECT view_name, table_name 
    FROM information_schema.view_table_usage
    WHERE table_name = 'customer_data';
""")
views = cur.fetchall()
if views:
    for view in views:
        print(f"View: {view[0]} references Table: {view[1]}")
else:
    print("No views referencing 'customer_data' found.")

cur.close()
conn.close()

=== Views Using Tables ===
No views referencing 'customer_data' found.